### ISSUE TITLE
Section 4.3 refers to Env 316

### ISSUE THREAD

**Issue by StephSchneider** [DavidRossHall/R4EnvChem#22]
'In all seriousness though, this document was only meant to introduce you to R markdown, and to make the case that you should use it for your ENV 316 coursework.'

Make it independent of the course?

**Comment by DavidRossHall** [comment]
Thanks for the reminder. I wrote that for ENV316 and need to clean it up.

**Comment by DavidRossHall** [comment]
Cleaned up rmarkdown chapter and updated example code and images.
